Authenticate/Client.Mvc/ViewModels/ClaimManager.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

namespace Client.Mvc.ViewModels
{
    public class ClaimManager
    {
        public List<ClaimViewer> Items { get; set; }

        public ClaimManager(HttpContext context, ClaimsPrincipal user)
        {
            Items = new List<ClaimViewer>();
            var claims = user.Claims.ToList();

            var idJsonToken = context.GetTokenAsync("id_token").GetAwaiter().GetResult();
            var accessJsonToken = context.GetTokenAsync("access_token").GetAwaiter().GetResult();

            AddTokenInfo("Identity Token", idJsonToken);
            AddTokenInfo("Access Token", accessJsonToken);
            AddTokenInfo("User Claims", claims);
        }

        public string AccessToken
        {
            get { return Items.SingleOrDefault(y => y.Name == "Access Token")?.Token; }
        }

        private void AddTokenInfo(string nameToken, string idTokenJson)
        {
            Items.Add(new ClaimViewer(nameToken, idTokenJson));
        }

        private void AddTokenInfo(string nameToken, IEnumerable<Claim> claims)
        {
            Items.Add(new ClaimViewer(nameToken, claims));
        }
    }
}

Authenticate/Client.Mvc/ViewModels/ClaimViewer.cs
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;

namespace Client.Mvc.ViewModels
{
    public class ClaimViewer
    {

        public ClaimViewer(string name, IEnumerable<Claim> claims)
        {
            Name = name;
            Claims = claims.ToList();
            Token = "N/A";  
        }

        public ClaimViewer(string name, string tokenJson)
        {
            Token = tokenJson;
            Name = name;
            Claims = ((JwtSecurityToken)new JwtSecurityTokenHandler().ReadToken(tokenJson)).Claims?.ToList();
        }

        public string Name { get; private set; }
        public List<Claim> Claims { get; private set; }
        public string Token { get; private set; }
    }
}

Authenticate/Client.Mvc/Controllers/SiteController.cs
using Client.Mvc.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace Client.Mvc.Controllers
{
    public class SiteController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public SiteController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public async Task<IActionResult> Secret()
        {
            var model = new ClaimManager(HttpContext, User);

            // Обращение к другому сервису с Bearer токеном
            try
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", model.AccessToken);
                var ordersApiSecret = await client.GetStringAsync("https://localhost:5001/site/secret");
                ViewBag.Message = ordersApiSecret;
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }

            return View(model);
        }

        [Authorize(Policy = "HasDateOfBirth")]
        public async Task<IActionResult> Secret1()
        {
            var model = new ClaimManager(HttpContext, User);

            return View(model);
        }

        [Authorize(Policy = "OlderThan10")]
        public async Task<IActionResult> Secret2()
        {
            var model = new ClaimManager(HttpContext, User);

            return View(model);
        }
    }
}

Authenticate/Client.Mvc/Views/Shared/_Menu.cshtml
<a asp-controller="Site" asp-action="Index">Index</a>
<a asp-controller="Site" asp-action="Secret">Secret</a>
<a asp-controller="Site" asp-action="Secret1">Secret1</a>
<a asp-controller="Site" asp-action="Secret2">Secret2</a>

Authenticate/Client.Mvc/Views/Site/Index.cshtml
<h1>Index</h1>

<partial name="_Menu"></partial>

Authenticate/Client.Mvc/Views/Site/Secret.cshtml
@using System.Security.Claims
@using Client.Mvc.ViewModels
@model Client.Mvc.ViewModels.ClaimManager
<style>
    body {
        background-color: #f1f1f1;
    }
    .content {
        width: 100%;
        padding: .5em;
        display: flex;
        flex-direction: row;
        font-family: sans-serif;
    }
    .column {
        flex: 1 1 0;
        margin: 0 2px;
    }
    .title {
        font-weight: bold;
        color: black;
        border: 1px solid #ccc;
        padding: 2px;
        margin: 1px;
        text-align: right;
        width: 7em;
        overflow: hidden;
        background-color: #fefefe;
        display: inline-block;
    }
    .value {
        color: black;
        border: 1px solid #ccc;
        padding: 1px 5px;
        margin: 1px;
        min-width: 20em;
        max-width: 20em;
        overflow: hidden;
        display: inline-block;
        color: #123ab8;
    }
    span {
        background-color: #fff;
    }
    h3 {
        padding: .5em;
        background-color: #cd37c3;
        color: white;
    }
        h3 b {
            color: yellow;
        }
</style>

<h1>Secret</h1>

<partial name="_Menu" />

<p>
    @ViewBag.Message
</p>

<div class="content">
    @foreach (var item in Model.Items)
    {
        <div class="column">

            <h3>
                @item.Name <b>@GetClaims(item).Count</b>
            </h3>

            <div>
                <p>
                    <textarea rows="10" cols="62" asp-for="@item.Token"></textarea>
                </p>
            </div>


            @foreach (var claim in GetClaims(item))
            {
                <span class="title" title="@claim.Type">@claim.Type:</span>
                <span class="value" title="@claim.Value">@claim.Value</span><br />
            }
        </div>
    }
</div>

@functions
{
    public List<Claim> GetClaims(ClaimViewer item)
    {
        if (item.Claims != null && item.Claims.Count > 0)
        {
            return item.Claims;
        }
        return new List<Claim>();
    }
}

Authenticate/Client.Mvc/Views/Site/Secret1.cshtml
@using System.Security.Claims
@using Client.Mvc.ViewModels
@model Client.Mvc.ViewModels.ClaimManager
<style>
    body {
        background-color: #f1f1f1;
    }
    .content {
        width: 100%;
        padding: .5em;
        display: flex;
        flex-direction: row;
        font-family: sans-serif;
    }
    .column {
        flex: 1 1 0;
        margin: 0 2px;
    }
    .title {
        font-weight: bold;
        color: black;
        border: 1px solid #ccc;
        padding: 2px;
        margin: 1px;
        text-align: right;
        width: 7em;
        overflow: hidden;
        background-color: #fefefe;
        display: inline-block;
    }
    .value {
        color: black;
        border: 1px solid #ccc;
        padding: 1px 5px;
        margin: 1px;
        min-width: 20em;
        max-width: 20em;
        overflow: hidden;
        display: inline-block;
        color: #123ab8;
    }
    span {
        background-color: #fff;
    }
    h3 {
        padding: .5em;
        background-color: #cd37c3;
        color: white;
    }
        h3 b {
            color: yellow;
        }
</style>

<h1>Secret 1</h1>

<partial name="_Menu" />

<p>
    @ViewBag.Message
</p>

<div class="content">
    @foreach (var item in Model.Items)
    {
        <div class="column">

            <h3>
                @item.Name <b>@GetClaims(item).Count</b>
            </h3>

            <div>
                <p>
                    <textarea rows="10" cols="62" asp-for="@item.Token"></textarea>
                </p>
            </div>


            @foreach (var claim in GetClaims(item))
            {
                <span class="title" title="@claim.Type">@claim.Type:</span>
                <span class="value" title="@claim.Value">@claim.Value</span><br />
            }
        </div>
    }
</div>

@functions
{
    public List<Claim> GetClaims(ClaimViewer item)
    {
        if (item.Claims != null && item.Claims.Count > 0)
        {
            return item.Claims;
        }
        return new List<Claim>();
    }
}

Authenticate/Client.Mvc/Views/Site/Secret2.cshtml
@using System.Security.Claims
@using Client.Mvc.ViewModels
@model Client.Mvc.ViewModels.ClaimManager
<style>
    body {
        background-color: #f1f1f1;
    }
    .content {
        width: 100%;
        padding: .5em;
        display: flex;
        flex-direction: row;
        font-family: sans-serif;
    }
    .column {
        flex: 1 1 0;
        margin: 0 2px;
    }
    .title {
        font-weight: bold;
        color: black;
        border: 1px solid #ccc;
        padding: 2px;
        margin: 1px;
        text-align: right;
        width: 7em;
        overflow: hidden;
        background-color: #fefefe;
        display: inline-block;
    }
    .value {
        color: black;
        border: 1px solid #ccc;
        padding: 1px 5px;
        margin: 1px;
        min-width: 20em;
        max-width: 20em;
        overflow: hidden;
        display: inline-block;
        color: #123ab8;
    }
    span {
        background-color: #fff;
    }
    h3 {
        padding: .5em;
        background-color: #cd37c3;
        color: white;
    }
        h3 b {
            color: yellow;
        }
</style>

<h1>Secret 2</h1>

<partial name="_Menu" />

<p>
    @ViewBag.Message
</p>

<div class="content">
    @foreach (var item in Model.Items)
    {
        <div class="column">

            <h3>
                @item.Name <b>@GetClaims(item).Count</b>
            </h3>

            <div>
                <p>
                    <textarea rows="10" cols="62" asp-for="@item.Token"></textarea>
                </p>
            </div>


            @foreach (var claim in GetClaims(item))
            {
                <span class="title" title="@claim.Type">@claim.Type:</span>
                <span class="value" title="@claim.Value">@claim.Value</span><br />
            }
        </div>
    }
</div>

@functions
{
    public List<Claim> GetClaims(ClaimViewer item)
    {
        if (item.Claims != null && item.Claims.Count > 0)
        {
            return item.Claims;
        }
        return new List<Claim>();
    }
}